/* OINP Employer Job Offer points.
   Extracted from the original tool, reading points from data-pts.
   Every card is either one select or one radio group. */

export const OINP_CARDS = [
  {
    id: "occ",
    title: "Occupation",
    max: "Max 19 points",
    sub: "Type a job title. Your NOC code sets both your TEER level and your occupational category, so this one answer scores two factors.",
    kind: "occupation",
    manualTeer: [
      { v: "", t: "Select TEER level" },
      { v: "9", t: "TEER 0 or 1 — management, or usually needs a university degree (9)" },
      { v: "6", t: "TEER 2 or 3 — college, apprenticeship or supervisory (6)" },
      { v: "0", t: "TEER 4 or 5 — high school or short term training (0)" },
    ],
    manualCategory: [
      { v: "", t: "Select category" },
      { v: "10", t: "Health occupations (10)" },
      { v: "8", t: "Trades, transport and equipment operators (8)" },
      { v: "6", t: "Natural and applied sciences (6)" },
      { v: "4", t: "Legislative and senior management (4)" },
      { v: "4", t: "Business, finance and administration (4)" },
      { v: "4", t: "Education, law, social, community and government services (4)" },
      { v: "4", t: "Natural resources, agriculture and related production (4)" },
      { v: "4", t: "Manufacturing and utilities (4)" },
      { v: "2", t: "Art, culture, recreation and sport (2)" },
      { v: "2", t: "Sales and service (2)" },
    ],
  },
  {
    id: "wage",
    title: "Compensation",
    max: "Max 15 points",
    sub: "The hourly wage your employer states on the job offer, before deductions.",
    kind: "select",
    options: [
      { v: "", t: "Select a wage band" },
      { v: "15", t: "$40.00 an hour or more (15)" },
      { v: "12", t: "$35.00 to $39.99 (12)" },
      { v: "10", t: "$30.00 to $34.99 (10)" },
      { v: "8", t: "$25.00 to $29.99 (8)" },
      { v: "5", t: "$20.00 to $24.99 (5)" },
      { v: "0", t: "Under $20.00 (0)" },
    ],
  },
  {
    id: "expjob",
    title: "Experience in the Offer Position",
    max: "Max 18 points",
    sub: "Months worked in the exact position named on your job offer.",
    kind: "select",
    options: [
      { v: "", t: "Select experience" },
      { v: "18", t: "More than 24 months (18)" },
      { v: "15", t: "13 to 24 months (15)" },
      { v: "12", t: "6 to 12 months (12)" },
      { v: "0", t: "Under 6 months (0)" },
    ],
  },
  {
    id: "expont",
    title: "Experience Anywhere in Ontario",
    max: "Max 12 points",
    sub: "Any Ontario work experience, counted separately from the offer position above.",
    kind: "select",
    options: [
      { v: "", t: "Select experience" },
      { v: "12", t: "More than 24 months (12)" },
      { v: "9", t: "13 to 24 months (9)" },
      { v: "6", t: "6 to 12 months (6)" },
      { v: "0", t: "Under 6 months (0)" },
    ],
  },
  {
    id: "expphys",
    title: "Medical Practice in Ontario",
    max: "Max 18 points",
    sub: "Cumulative months of practice. It does not need to be continuous.",
    kind: "select",
    options: [
      { v: "", t: "Select experience" },
      { v: "18", t: "2 years or more, cumulative (18)" },
      { v: "15", t: "13 to 24 months (15)" },
      { v: "12", t: "6 to 12 months (12)" },
      { v: "0", t: "Under 6 months (0)" },
    ],
  },
  {
    id: "earn",
    title: "Canadian Tax History",
    max: "Max 8 points",
    sub: "Your highest single year of income in the last five tax years, as assessed by the CRA.",
    kind: "select",
    options: [
      { v: "", t: "Select an income band" },
      { v: "8", t: "$70,000 or more in a year (8)" },
      { v: "6", t: "$50,000 to $69,999 (6)" },
      { v: "4", t: "$30,000 to $49,999 (4)" },
      { v: "0", t: "Under $30,000, or no Canadian tax history (0)" },
    ],
  },
  {
    id: "status",
    title: "Status in Canada",
    max: "Max 10 points",
    sub: "Your current valid immigration status, if any.",
    kind: "radio",
    options: [
      { v: "10", t: "Valid Canadian work permit" },
      { v: "5", t: "Valid Canadian study permit" },
      { v: "0", t: "Neither" },
    ],
  },
  {
    id: "edu",
    title: "Highest Credential",
    max: "Max 10 points",
    sub: "Only your single highest completed credential counts.",
    kind: "select",
    options: [
      { v: "", t: "Select credential" },
      { v: "10", t: "Doctorate, or a degree in medicine, dentistry, veterinary medicine or optometry (10)" },
      { v: "8", t: "Master’s degree (8)" },
      { v: "6", t: "University certificate or diploma above a bachelor’s (6)" },
      { v: "6", t: "Bachelor’s degree or equivalent (6)" },
      { v: "5", t: "Ontario College Graduate Certificate (5)" },
      { v: "5", t: "University certificate or diploma below a bachelor’s (5)" },
      { v: "5", t: "College, CEGEP or other non university credential (5)" },
      { v: "5", t: "Apprenticeship or trades certificate or diploma (5)" },
      { v: "0", t: "Less than a college or trade certificate (0)" },
    ],
  },
  {
    id: "cancred",
    title: "Canadian Credentials",
    max: "Max 10 points",
    sub: "Credentials earned at a Canadian institution, scored on top of your highest credential above.",
    kind: "radio",
    options: [
      { v: "10", t: "More than one Canadian post secondary credential" },
      { v: "5", t: "One Canadian post secondary credential" },
      { v: "0", t: "None" },
    ],
  },
  {
    id: "clb",
    title: "Language Level",
    max: "Max 15 points",
    sub: "Use your stronger official language, then take the lowest of your four abilities on that test: listening, reading, writing, speaking.",
    kind: "select",
    options: [
      { v: "", t: "Select CLB level" },
      { v: "15", t: "CLB 9 or higher (15)" },
      { v: "12", t: "CLB 8 (12)" },
      { v: "8", t: "CLB 7 (8)" },
      { v: "4", t: "CLB 6 (4)" },
      { v: "0", t: "CLB 5 or lower (0)" },
    ],
  },
  {
    id: "lang2",
    title: "Official Languages",
    max: "Max 10 points",
    sub: "Scored on top of your CLB level above.",
    kind: "radio",
    options: [
      { v: "10", t: "Both English and French at CLB 6 or higher" },
      { v: "5", t: "One official language at CLB 6 or higher" },
      { v: "0", t: "Neither at CLB 6 or higher" },
    ],
  },
  {
    id: "region",
    title: "Work Location",
    max: "Max 15 points",
    sub: "Use the work location on the job offer, not your home address. Physicians: use the practice address registered to your OHIP billing number.",
    kind: "select",
    options: [
      { v: "", t: "Select a census division" },
      { v: "15", t: "Sudbury, Greater Sudbury, Thunder Bay, Nipissing, Parry Sound" },
      { v: "15", t: "Muskoka, Haliburton, Manitoulin, Timiskaming, Cochrane" },
      { v: "15", t: "Algoma, Rainy River, Kenora" },
      { v: "10", t: "Ottawa, Frontenac, Lanark, Leeds and Grenville, Renfrew" },
      { v: "10", t: "Hastings, Kawartha Lakes, Lennox and Addington, Northumberland" },
      { v: "10", t: "Peterborough, Prescott and Russell, Prince Edward" },
      { v: "10", t: "Stormont, Dundas and Glengarry" },
      { v: "10", t: "Hamilton, Niagara, Brant, Haldimand Norfolk" },
      { v: "10", t: "Middlesex, Elgin, Oxford, Perth, Huron, Bruce" },
      { v: "10", t: "Essex, Chatham Kent, Lambton" },
      { v: "10", t: "Waterloo, Wellington, Dufferin, Grey, Simcoe" },
      { v: "5", t: "Peel, York, Durham, Halton" },
      { v: "0", t: "City of Toronto" },
    ],
  },
];

export const OINP_PATHWAY_OPTIONS = [
  { v: "skilled", t: "Ontario job offer, skilled occupation  NOC TEER 0 to 3" },
  { v: "essential", t: "Ontario job offer, essential occupation  NOC TEER 4 or 5" },
  { v: "physician", t: "Self employed physician in Ontario  Practice experience replaces the wage factor" },
];
